#! /bin/bash
echo
echo
echo
echo "______________S T A R T   J O B_____________________"
echo
echo
echo ' PL/1  ----->  Asswmbler    c o m p i l i n g'
echo "continue?(y/n)"
read OTV
if [ "$OTV" = "y" ] 
then
 echo
 ./komppl.exe  examppl.pli
else
 echo
 exit
fi
echo
echo
echo
echo ' Assembler  ----->  Object image   c o m p i l i n g'
echo "continue?(y/n)"
read OTV
if [ "$OTV" = "y" ] 
then
 echo
 ./kompassr.exe examppl.ass
else
 echo
 exit
fi
echo
echo
echo
echo ' Load, run and debug Object image  '
echo "continue?(y/n)"
read OTV
if [ "$OTV" = "y" ] 
then
 echo
 ./absloadm.exe spis.mod
else
 echo
 exit
fi
echo
echo
echo
echo "______________F I N I S H     J O B__________________"
